### ISSUE TITLE
Consider NVMe-only build

### ISSUE THREAD

**Issue by chinigo** [chinigo/pc_build#4]
1TB will hold ~15-20 AAA games, which is probably sufficient. If you want additional space, you can go with a SATA SSD or HDD. But you could also go with a second NVMe drive.

The 2TB version of the Samsung 970 Evo NVMe is like 300% the price of the 1TB version, but why not buy two 1TB drives?

The ASRock X570 has three M.2 sockets that you could put an NVMe drive into. Your GPU might not leave enough clearance for one of those sockets, but the other two should be free.

<img width="857" alt="ASRock M 2 sockets" src="https://user-images.githubusercontent.com/537221/72005518-c8a53f00-321b-11ea-94f9-70ff5d741b83.png">

From [the manual](http://asrock.pc.cdn.bitgravity.com/Manual/X570%20Taichi.pdf):

> • 1 x Hyper M.2 Socket (M2_1), supports M Key type 2242/2260/2280 M.2 SATA3 6.0 Gb/s module and M.2 PCI Express module up to Gen4x4 (64 Gb/s) (with Matisse) or Gen3x4 (32 Gb/s) (with Pinnacle Ridge and Picasso)*
>
> • 1 x Hyper M.2 Socket (M2_2), supports M Key type 2260/2280 M.2 PCI Express module up to Gen4x4 (64 Gb/s)*
>
> • 1 x Hyper M.2 Socket (M2_3), supports M Key type 2230/2242/2260/2280/22110 M.2 SATA3 6.0 Gb/s module and M.2 PCI Express module up to Gen4x4 (64 Gb/s)*
>
> * *If M2_3 is occupied, PCIE5 slot will be disabled*

(The Ryzen 3900X is a [Matisse-series CPU](https://en.wikipedia.org/wiki/Ryzen#CPUs:_Matisse_(Ryzen)_and_Castle_Peak_(Ryzen_Threadripper)) btw).

**Comment by ryanmcgarvey** [comment]
I've got a spare 500GB EVO, so i think 1.5TB over 2 drives is sufficient for now.

**Comment by chinigo** [comment]
Concur!
